from enum import Enum


class TodoStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"


class EisenhowerStatus(str, Enum):
    URGENT_IMPORTANT = "URGENT_IMPORTANT"
    NOT_URGENT_IMPORTANT = "NOT_URGENT_IMPORTANT"
    URGENT_NOT_IMPORTANT = "URGENT_NOT_IMPORTANT"
    NOT_URGENT_NOT_IMPORTANT = "NOT_URGENT_NOT_IMPORTANT"
